[build]
target = "arm-unknown-linux-gnueabihf" # Raspberry Pi build target.

[target.arm-unknown-linux-gnueabihf]
# Custom built via https://solarianprogrammer.com/2018/05/06/building-gcc-cross-compiler-raspberry-pi/
linker = "/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-gcc"

[env]
# Additionally openssl. https://thekerneldiaries.wordpress.com/2016/06/14/cross-compile-openssl-for-your-raspberry-pi/
# Configure with -latomic
OPENSSL_DIR = "/opt/cross-pi-openssl/"