name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  cross_compile_raspberry_pi_w:
    name: Cross compile Raspberry Pi W
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tyhdefu/armv6_rust_raspi_0w:0.0.2
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
