name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  cross_compile_raspberry_pi_w:
    name: Cross compile Raspberry Pi W
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tyhdefu/armv6_rust_raspi_0w:0.0.8
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            target/**/build
            target/**/deps
          key: cross-compile-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - run: cargo build --target arm-unknown-linux-gnueabihf --release
      - name: Cross compiled raspberry pi 0W file
        uses: actions/upload-artifact@v3
        with:
          name: follow_heating_pi_0w
          path: target/arm-unknown-linux-gnueabihf/release/follow_heating
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          target/**/build
          target/**/deps
        key: normal-compile-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/London"
    - name: Run tests
      run: cargo test --verbose
